name: Update Readme.md

 # Controls when the workflow will run
on:
   # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  schedule:
     # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 1,10,20,30 * *'

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch commits
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://api.github.com/search/commits?q=author:EricHsia7'
        file: 'commits.json'

    - name: Fetch Pulls
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://api.github.com/search/issues?q=author:EricHsia7+type:pr'
        file: 'prs.json'

    - name: Fetch Issue
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://api.github.com/search/issues?q=author:EricHsia7+type:issue'
        file: 'issue.json'

    - name: list file
      run: ls
    
    - name: Get commits
      id: set_var
      run: |
        content=`cat ./commits.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=commitsjson::$content"

    - run: |
        echo "${{fromJson(steps.set_var.outputs.commitsjson).total_count}}"


