name: Update Readme.md

 # Controls when the workflow will run
on:
   # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  schedule:
     # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 1,10,20,30 * *'

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch API
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://fake-movie-database-api.herokuapp.com/api?s=batman'
        file: 'data.json'

    - name: list file
      run: ls
    
    - name: get commits total count
      id: commitsdata
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'data.json'
        prop_path: 'total_count'

    - run: echo ${{steps.commitsdata.outputs.prop}} 

